### ISSUE TITLE
Guidance on adding other GDO Modules .. Fan etc 

### ISSUE THREAD

**Issue by SunBum12** [Madj42/ryobi_gdo3#7]
Hi!

Thank you for making this available.

Both the Door and Light toggles work perfectly.

I would like to add support for the other Add-on Modules like Fan, Speaker, Air, Plug reel etc

Can you offer any pointers to get me started?

Thank you!

**Comment by Madj42** [comment]
You'll have to look at what I did for the light as an example.  It's messy
but works.  You will need to look at the json that is received from  the
service in order to find the on/off parameters or whatever you want to pull
for the integration.  I do not have anything besides the battery which I
don't really care to add.  To be honest a lot of this is not the best way
as it would be more efficient to use websockets to interact versus the web
service calls.  This is most mostly the reason I haven't expanded this more.

**Comment by Madj42** [comment]
Closing.

**Comment by Madj42** [comment]
Closing.
